// IndexNow: ping Bing (and IndexNow partners) that URLs changed, for instant indexing.
// Run after deploying the app to the VPS: node scripts/indexnow-submit.mjs
// This is a Flask app; the sitemap is generated by a route (/sitemap.xml), so we
// fetch the live sitemap. The key file is served at the host root by the Flask
// route added in app.py (static/<KEY>.txt exposed at /<KEY>.txt).
const KEY = "1ab61c61f3df80b46b21058ceccede55";
const HOST = "glitchtexteffect.com";
async function locs(url, depth = 0) {
  const out = [];
  const xml = await (await fetch(url)).text();
  const isIndex = /<sitemapindex/i.test(xml);
  for (const m of xml.matchAll(/<loc>([^<]+)<\/loc>/g)) {
    const loc = m[1].trim();
    if (isIndex && depth < 3) out.push(...await locs(loc, depth + 1));
    else if (!isIndex) out.push(loc);
  }
  return out;
}
const list = [...new Set(await locs(`https://${HOST}/sitemap.xml`))];
if (!list.length) { console.error("no sitemap URLs found from live sitemap"); process.exit(1); }
const body = { host: HOST, key: KEY, keyLocation: `https://${HOST}/${KEY}.txt`, urlList: list.slice(0, 10000) };
const r = await fetch("https://api.indexnow.org/indexnow", {
  method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body),
});
console.error(`IndexNow submitted ${list.length} URLs -> HTTP ${r.status}`);
